import type { Metadata } from 'next';
import Link from 'next/link';
import MorseAudioVoiceTranslator from '@/components/MorseAudioVoiceTranslator';
import WpContent from '@/components/WpContent';
import { AD_UNIT_IDS } from '@/lib/ads';
import { buildRobotsContent } from '@/lib/metadata';
import { buildYoastGraph } from '@/lib/schema';
import { SITE_NAME, SITE_URL, toAbsoluteUrl } from '@/lib/site';

const PATH = '/morse-code-audio-translator/';
const PAGE_URL = `${SITE_URL}${PATH}`;
const IMAGE_URL = toAbsoluteUrl('/wp-content/uploads/2025/11/Play-Morse-Code-Audio-1024x407.png');
const IMAGE_ALT = 'Play Morse Code Audio';
const TITLE = 'Morse Code Audio Translator: Voice, Upload, and Morse Audio Controls';
const DESCRIPTION = 'Use our free audio to Morse code tool to listen with speech recognition or analyse uploaded Morse audio while controlling WPM, Farnsworth speed, frequency, and thresholds.';
const PUBLISHED_TIME = '2026-04-25T10:00:00.000Z';
const MODIFIED_TIME = '2026-04-25T10:00:00.000Z';
const FAQ_ITEMS = [
  {
    question: 'Can I speak and upload Morse audio in the same tool?',
    answer: 'Yes. This page lets you either listen with browser speech recognition or upload an audio file containing Morse code for analysis.',
  },
  {
    question: 'Is this audio to Morse code tool free?',
    answer: 'Yes. You can use it in your browser without creating an account or installing extra software.',
  },
  {
    question: 'Can I control WPM, Farnsworth speed, and frequency?',
    answer: 'Yes. The tool now exposes WPM, Farnsworth WPM, frequency, minimum volume, maximum volume, and volume threshold controls.',
  },
  {
    question: 'Can I play uploaded audio and generated Morse output?',
    answer: 'Yes. You can play or stop the uploaded file and also play the Morse output generated by the tool.',
  },
  {
    question: 'Which browsers support the listen feature?',
    answer: 'The listen mode works best in browsers that support the Web Speech API, such as Chrome, Edge, and Safari on supported devices.',
  },
];

const CONTENT_HTML = `
  <p>If you’ve ever looked at dots and dashes and thought, “I get the idea, but what does it actually sound like?”, you’re in the right place.</p>
  <p>Many learners find they make the most progress when practising Morse through sound rather than visual patterns. That’s exactly why I recommend using a Morse code audio translator.</p>
  <p>With this free tool, you can type plain text and hear it as authentic Morse beeps, paste Morse and play it back to check your timing, practise letters and common signals, and learn the rhythm the way real operators do. No downloads. No sign-ups. Just type and listen.</p>
  <h2>What is a Morse Code Audio Translator?</h2>
  <p>A Morse code audio translator converts either text to Morse audio or Morse symbols to playable timing patterns. The system transforms a message like <strong>HELLO WORLD</strong> into a sequence of Morse sounds:</p>
  <ul>
    <li><strong>Dots (dits):</strong> short tones</li>
    <li><strong>Dashes (dahs):</strong> longer tones</li>
    <li><strong>Gaps:</strong> silent pauses that create the language of Morse</li>
  </ul>
  <p>What makes audio special is that Morse is fundamentally a timing-based system, not a visual one. You don’t truly know Morse until your ear starts recognising sound patterns without consciously translating each letter.</p>

  <h2>How To Use Morse Code Audio Translator</h2>
  <figure>
    <img width="1024" height="407" src="/images/Audio-to-Morse-code-tool.png" alt="Play Morse Code Audio" />
  </figure>
  <ol class="wp-full-width-list">
    <li><strong>Choose your input method.</strong> Press <strong>Listen</strong> to use your microphone and speech recognition, or press <strong>Upload</strong> to analyse an audio file containing Morse code.</li>
    <li><strong>Speak or upload clearly.</strong> If you use the listen mode, speak naturally and let the tool capture your words. If you upload a file, choose a clear Morse recording with minimal background noise for better decoding.</li>
    <li><strong>Adjust the controls if needed.</strong> Use <strong>WPM</strong>, <strong>Farnsworth WPM</strong>, <strong>Frequency (Hz)</strong>, <strong>Minimum volume</strong>, <strong>Maximum volume</strong>, and <strong>Volume threshold</strong> to fine-tune playback and uploaded-audio analysis.</li>
    <li><strong>Review the output.</strong> The tool will show the recognised text and Morse code so you can compare, practise, or verify the result immediately.</li>
    <li><strong>Play, copy, or clear.</strong> Use <strong>Play</strong> or <strong>Play Morse</strong> to hear the audio, use <strong>Copy</strong> to save the text or Morse output, and use <strong>Clear Message</strong> to reset the tool for the next test.</li>
  </ol>

  <h2>Why convert Morse code to audio?</h2>
  <p>Most people start by memorising Morse visually. That works for a few characters, but it breaks down fast when you try to go faster. Audio practice builds what operators often call the Morse ear, where you recognise the sound pattern directly.</p>
  <table>
    <tbody>
      <tr><th>Use case</th><th>Why audio helps</th></tr>
      <tr><td>Learning</td><td>Your brain recognises rhythm faster than it recalls dot-dash drawings.</td></tr>
      <tr><td>Practice</td><td>Ideal for CW training, mock tests, and speed-building.</td></tr>
      <tr><td>Verification</td><td>You can confirm your Morse is correct by hearing it played back.</td></tr>
      <tr><td>Education</td><td>Great for classroom demos and STEM history lessons.</td></tr>
      <tr><td>Hobby</td><td>Useful for puzzles, geocaching, jewellery messages, and maker projects.</td></tr>
      <tr><td>Emergency basics</td><td>Learning SOS and a few key patterns can be genuinely useful.</td></tr>
    </tbody>
  </table>

  <h2>Morse code timing rules</h2>
  <p>Morse isn’t just dots and dashes. It’s precise timing. If you get spacing wrong, letters blur into each other. Here are the standard International Morse timing rules.</p>
  <table>
    <tbody>
      <tr><th>Element</th><th>Units</th></tr>
      <tr><td>Dot (dit)</td><td>1</td></tr>
      <tr><td>Dash (dah)</td><td>3</td></tr>
      <tr><td>Gap between dits/dahs inside a character</td><td>1</td></tr>
      <tr><td>Gap between letters</td><td>3</td></tr>
      <tr><td>Gap between words</td><td>7</td></tr>
    </tbody>
  </table>

  <h2>Morse Code alphabet (A to Z)</h2>
  <p>If you’re practising, learning sound patterns in pairs helps because they reinforce each other.</p>
  <table>
    <tbody>
      <tr><th>Letter</th><th>Code</th><th>Letter</th><th>Code</th></tr>
      <tr><td>A</td><td>.-</td><td>N</td><td>-.</td></tr>
      <tr><td>B</td><td>-...</td><td>O</td><td>---</td></tr>
      <tr><td>C</td><td>-.-.</td><td>P</td><td>.--.</td></tr>
      <tr><td>D</td><td>-..</td><td>Q</td><td>--.-</td></tr>
      <tr><td>E</td><td>.</td><td>R</td><td>.-.</td></tr>
      <tr><td>F</td><td>..-.</td><td>S</td><td>...</td></tr>
      <tr><td>G</td><td>--.</td><td>T</td><td>-</td></tr>
      <tr><td>H</td><td>....</td><td>U</td><td>..-</td></tr>
      <tr><td>I</td><td>..</td><td>V</td><td>...-</td></tr>
      <tr><td>J</td><td>.---</td><td>W</td><td>.--</td></tr>
      <tr><td>K</td><td>-.-</td><td>X</td><td>-..-</td></tr>
      <tr><td>L</td><td>.-..</td><td>Y</td><td>-.--</td></tr>
      <tr><td>M</td><td>--</td><td>Z</td><td>--..</td></tr>
    </tbody>
  </table>
  <p>Practical note: E and T are the shortest because they’re among the most common letters in English. Morse was designed for efficiency.</p>

  <h2>Morse Code numbers (0 to 9)</h2>
  <p>Numbers are highly structured and easier once you spot the symmetry.</p>
  <table>
    <tbody>
      <tr><th>Number</th><th>Code</th><th>Number</th><th>Code</th></tr>
      <tr><td>1</td><td>.----</td><td>6</td><td>-....</td></tr>
      <tr><td>2</td><td>..---</td><td>7</td><td>--...</td></tr>
      <tr><td>3</td><td>...--</td><td>8</td><td>---..</td></tr>
      <tr><td>4</td><td>....-</td><td>9</td><td>----.</td></tr>
      <tr><td>5</td><td>.....</td><td>0</td><td>-----</td></tr>
    </tbody>
  </table>

  <h2>Common punctuation in Morse code</h2>
  <table>
    <tbody>
      <tr><th>Symbol</th><th>Code</th></tr>
      <tr><td>Period .</td><td>.-.-.-</td></tr>
      <tr><td>Comma ,</td><td>--..--</td></tr>
      <tr><td>Question mark ?</td><td>..--..</td></tr>
      <tr><td>Apostrophe '</td><td>.----.</td></tr>
      <tr><td>Exclamation !</td><td>-.-.--</td></tr>
      <tr><td>Slash /</td><td>-..-.</td></tr>
      <tr><td>Hyphen -</td><td>-....-</td></tr>
      <tr><td>Parentheses ( )</td><td>-.--.-</td></tr>
      <tr><td>Colon :</td><td>---...</td></tr>
      <tr><td>Semicolon ;</td><td>-.-.-.</td></tr>
      <tr><td>Equals =</td><td>-...-</td></tr>
      <tr><td>Plus +</td><td>.-.-.</td></tr>
      <tr><td>At @</td><td>.--.-.</td></tr>
    </tbody>
  </table>

  <h2>Common Morse audio examples you can try right now</h2>
  <p>These are strong starter inputs because they have memorable rhythms.</p>
  <table>
    <tbody>
      <tr><th>Text</th><th>Morse</th></tr>
      <tr><td><a href="https://morse-codetranslator.com/sos-in-morse-code/">SOS</a></td><td>... --- ...</td></tr>
      <tr><td>OK</td><td>--- -.-</td></tr>
      <tr><td><a href="https://morse-codetranslator.com/hello-in-morse-code/">HELLO</a></td><td>.... . .-.. .-.. ---</td></tr>
      <tr><td><a href="https://morse-codetranslator.com/yes-in-morse-code/">YES</a></td><td>-.-- . ...</td></tr>
      <tr><td><a href="https://morse-codetranslator.com/no-in-morse-code/">NO</a></td><td>-. ---</td></tr>
      <tr><td><a href="https://morse-codetranslator.com/love-in-morse-code/">LOVE</a></td><td>.-.. --- ...- .</td></tr>
    </tbody>
  </table>
  <p>If you’re brand new, play SOS until you can identify it instantly. That rhythm becomes a reference point for everything else.</p>

  <h2>Text to Morse Code Audio features</h2>
  <p>I evaluate Morse audio tools according to the same criteria I use to assess real listening exercises: clear sound, accurate timing, and a simple interface that makes practice easy.</p>
  <ul>
    <li><strong>Instant conversion:</strong> type and play immediately.</li>
    <li><strong>Supports learning and checking:</strong> enter text to encode or enter Morse to play it back.</li>
    <li><strong>Clear tone:</strong> most learners do best around 600&ndash;800 Hz, but this tool lets you adjust pitch.</li>
    <li><strong>Works on desktop and mobile:</strong> practise in any modern browser.</li>
    <li><strong>Free and privacy-friendly:</strong> no account needed.</li>
    <li><strong>Downloadable practice:</strong> export MP3 audio when you want a file to keep.</li>
  </ul>

  <h2>Who uses a Morse code audio translator?</h2>
  <table>
    <tbody>
      <tr><th>Audience</th><th>Typical use</th></tr>
      <tr><td>Students</td><td>Communication history, wartime technology, and signal projects.</td></tr>
      <tr><td>Amateur radio operators</td><td>CW practice, callsign drills, and on-air confidence.</td></tr>
      <tr><td>Scouts and Guides</td><td>Badge work and basic signalling skills.</td></tr>
      <tr><td>Teachers</td><td>Interactive classroom demonstrations.</td></tr>
      <tr><td>Puzzle solvers</td><td>Escape rooms, ARGs, and geocaching clues.</td></tr>
      <tr><td>Film and game creators</td><td>Authentic sound design and props.</td></tr>
      <tr><td>Makers</td><td>Arduino projects, LEDs, buzzers, and training kits.</td></tr>
      <tr><td>Preparedness learners</td><td>Backup signalling basics like SOS and short phrases.</td></tr>
    </tbody>
  </table>

  <h2>Morse code audio and UK amateur radio</h2>
  <p>From hands-on experience in the community, CW practice still matters because narrow-band Morse can remain readable when voice fails, it works efficiently with modest equipment, and it is still a living tradition. Many UK clubs continue to run CW sessions, and organisations like the RSGB still promote training resources and operating skills.</p>

  <h2>How Morse code speed works</h2>
  <p>Morse speed is measured in WPM (words per minute). The standard reference word is <strong>PARIS</strong>, chosen because it represents a typical word length in Morse timing.</p>
  <table>
    <tbody>
      <tr><th>Level</th><th>WPM</th><th>What it feels like</th></tr>
      <tr><td>Beginner</td><td>5 to 10</td><td>Enough time to think; good for fundamentals.</td></tr>
      <tr><td>Improving</td><td>12 to 18</td><td>Recognition starts replacing counting.</td></tr>
      <tr><td>Comfortable</td><td>20+</td><td>You hear patterns as sounds, not dots and dashes.</td></tr>
      <tr><td>Advanced</td><td>30 to 40+</td><td>Fast conversational CW for experienced operators.</td></tr>
    </tbody>
  </table>

  <h2>Tips for learning Morse code with audio</h2>
  <ol>
    <li><strong>Start with the highest-frequency letters.</strong> Learn E, T, A, O, I, N, S, H, and R first.</li>
    <li><strong>Practise daily.</strong> Aim for 10 to 15 minutes rather than long, tiring sessions.</li>
    <li><strong>Learn the sound, not the symbol.</strong> Hear A as one pattern rather than consciously counting dot-dash.</li>
    <li><strong>Use real-life inputs.</strong> Try your name, your callsign, or short words like THE, AND, YOU.</li>
    <li><strong>Use a simple two-week restart plan.</strong></li>
  </ol>
  <table>
    <tbody>
      <tr><th>Days</th><th>Focus</th><th>Practice ideas</th></tr>
      <tr><td>1 to 3</td><td>E, T, A, N</td><td>E T A N, TEN, ANT</td></tr>
      <tr><td>4 to 7</td><td>I, M, S, O</td><td>IS, SO, AIM, MOON</td></tr>
      <tr><td>8 to 10</td><td>R, H, D, K</td><td>HER, HARD, DARK</td></tr>
      <tr><td>11 to 14</td><td>Numbers 1 to 5</td><td>1 2 3 4 5 and simple mixes</td></tr>
    </tbody>
  </table>

  <h2>Frequently asked questions</h2>
  <h3>How do I convert text to Morse code audio?</h3>
  <p>Type your message into the input box and press Play. The tool instantly converts each character into Morse timing and plays the audio.</p>
  <h3>Is this Morse code audio translator free?</h3>
  <p>Yes. You should be able to use it without accounts, trials, or feature locks.</p>
  <h3>Can I download the Morse audio?</h3>
  <p>Yes. This translator includes MP3 export, so you can save a practice file after generating your message.</p>
  <h3>What does SOS sound like in Morse code?</h3>
  <p>SOS is ... --- ... In audio, it’s three short beeps, three long beeps, and three short beeps. It’s designed to be unmistakable.</p>
  <h3>What speed is the audio?</h3>
  <p>This tool lets you adjust playback speed in WPM and use wider Farnsworth spacing so beginners can learn without losing character rhythm.</p>
  <h3>Can this tool convert Morse audio back to text?</h3>
  <p>This page is focused on encoding text to Morse audio and playing Morse symbols. Audio-to-text decoding needs a different kind of tool that analyses incoming sound, background noise, tone frequency, and timing variation.</p>

  <p>For more practice, see our guides on <a href="https://morse-codetranslator.com/how-to-learn-morse-code/">how to learn Morse code</a>, <a href="https://morse-codetranslator.com/how-does-morse-code-work/">how Morse code works</a>, <a href="https://morse-codetranslator.com/morse-code-letters/">Morse code letters</a>, and <a href="https://morse-codetranslator.com/morse-code-numbers/">Morse code numbers</a>.</p>
`;

export const dynamic = 'force-static';

export function generateMetadata(): Metadata {
  const robotsContent = buildRobotsContent(undefined, { index: true, follow: true });

  return {
    title: TITLE,
    description: DESCRIPTION,
    keywords: [
      'Morse code audio translator',
      'text to Morse audio',
      'Morse code sound',
      'Morse code player',
      'learn Morse by sound',
      SITE_NAME,
    ],
    alternates: { canonical: PAGE_URL },
    openGraph: {
      title: TITLE,
      description: DESCRIPTION,
      url: PAGE_URL,
      siteName: 'Morse',
      type: 'article',
      locale: 'en_US',
      publishedTime: PUBLISHED_TIME,
      modifiedTime: MODIFIED_TIME,
      images: [{
        url: IMAGE_URL,
        width: 1024,
        height: 407,
        alt: IMAGE_ALT,
        type: 'image/png',
      }],
    },
    twitter: {
      card: 'summary_large_image',
      title: TITLE,
      description: DESCRIPTION,
      images: [IMAGE_URL],
    },
    other: {
      robots: robotsContent,
      'og:image:secure_url': IMAGE_URL,
      'og:image:width': '1024',
      'og:image:height': '407',
      'og:image:alt': IMAGE_ALT,
      'og:image:type': 'image/png',
      'og:updated_time': MODIFIED_TIME,
      'article:published_time': PUBLISHED_TIME,
      'article:modified_time': MODIFIED_TIME,
      'twitter:label1': 'Time to read',
      'twitter:data1': '8 minutes',
      'meta-keywords': 'Morse code audio translator, text to Morse audio, Morse code sound, Morse code player, learn Morse by sound',
    },
  };
}

export default function MorseCodeAudioTranslatorPage() {
  const yoastGraph = buildYoastGraph({
    url: PAGE_URL,
    title: 'Morse Code Audio Translator',
    description: DESCRIPTION,
    imageUrl: IMAGE_URL,
    imageAlt: IMAGE_ALT,
    imageWidth: 1024,
    imageHeight: 407,
    imageType: 'image/png',
    publishedTime: PUBLISHED_TIME,
    modifiedTime: MODIFIED_TIME,
    articleLike: true,
    breadcrumbs: [
      { name: 'Home', item: SITE_URL },
      { name: 'Morse Code Audio Translator', item: PAGE_URL },
    ],
    faqItems: FAQ_ITEMS,
  });

  return (
    <article className="py-10 is-page-entry">
      <nav className="max-w-6xl mx-auto px-5 text-xs text-ink-500 mb-6 flex items-center gap-2 flex-wrap">
        <Link href="/" className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-white/70 backdrop-blur border border-ink-300/40 hover:bg-white text-ink-700 hover:text-brand-dark transition font-semibold">
          <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><path d="M3 12l9-9 9 9M5 10v10h4v-6h6v6h4V10"/></svg>
          Home
        </Link>
        <span className="text-ink-300">›</span>
        <span className="text-ink-900 font-bold truncate max-w-xs">Morse Code Audio Translator</span>
      </nav>

      <section className="max-w-6xl mx-auto px-5 mb-8">
        <h1 className="font-display text-4xl sm:text-5xl font-black tracking-tight text-ink-950 mb-6">Morse Code Audio Translator</h1>
        <p className="text-base sm:text-lg text-ink-700 max-w-3xl mb-6">Use the tool below to speak into your microphone or upload Morse audio, then review, play, and refine the results in your browser.</p>
        <MorseAudioVoiceTranslator />
      </section>

      <div id={AD_UNIT_IDS.inContentLazy} />

      <WpContent html={CONTENT_HTML} withInContentAds maxLazyRepeaters={100} />

      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(yoastGraph) }} />
    </article>
  );
}